{
    'name': 'Distribution''s Wholesale shop',
    'author': 'Bakum Viacheslav',
    'website': 'https://ugears.ua',
    'summary': 'Order your products online',
    'category': 'Sales/Distribution Management',
    'version': '16.0.0.1',
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'depends': [
        'ug_base_distrib',
        'website_sale',
    ],
    'data': [
        'views/templates.xml',
        'views/product_public.xml',
        'views/actions.xml',
        'views/start_shop.xml',
        'views/menu.xml',
        'security/wholesale_security.xml',
        'security/ir.model.access.csv',
        'data/packages_sizes_data.xml',
        'views/packages_sizes.xml',
        'views/distrib_places.xml',
        'views/distributors.xml',
        'views/import_order.xml',
        'views/sales_order.xml',
        'views/distrib_move.xml',
        'views/config_settings_views.xml',
        'report/order_distrib_template.xml',
        'report/order_distrib_action.xml',
        'report/report_distrib_quantity.xml',
        'views/mail_template_data.xml',
        'report/invoice_distrib_template.xml',
        'report/invoice_distrib_action.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'ug_wholesale_shop/static/src/js/website_sale_override.js',
            # ('replace', 'website_sale/static/src/js/website_sale.js', 'ug_wholesale_shop/static/src/js/website_sale.js'),
            ('replace', 'website_sale/static/src/js/website_sale_utils.js', 'ug_wholesale_shop/static/src/js/website_sale_utils.js'),
            'ug_wholesale_shop/static/src/js/variant_mixin.js',
            # 'ug_wholesale_shop/static/src/js/website_sale_override.js',
            'ug_wholesale_shop/static/src/js/wholesale_calculator.js',
        ],
        'web.assets_backend': [
            'ug_wholesale_shop/static/src/views/import_order_controller.js',
            'ug_wholesale_shop/static/src/views/import_order_view.js',
            'ug_wholesale_shop/static/src/views/import_order_button.xml',
            'ug_wholesale_shop/static/src/js/start_shop_tmpl.xml',
            'ug_wholesale_shop/static/src/js/start_shop.js',
        ],
    },
    "external_dependencies": {
        "python": ["rectpack"]
    },
}
