from . import website
from . import pricelist
from . import product_category
from . import irhttp
from . import divisions
from . import res_partner
from . import discount
from . import delivery
from . import sale_order
