{
    'name': 'Distribution Base',
    'author': 'Bakum Viacheslav',
    'website': 'https://ugears.ua',
    'summary': 'Provides a base for adding distribution support to models',
    'category': 'Sales/Distribution Management',
    'version': '16.0.0.1',
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'data': [
        'security/distrib_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/actions.xml',
        'views/menu.xml',
        'views/distrib_move.xml',
        'views/distrib.xml',
        'views/statistic.xml',
        'views/quants.xml',
        'views/currency_views.xml',
        'views/product_public.xml',
        'views/product_category.xml',
        'views/pricelist_view.xml',
        'views/user_view.xml',
        'views/partner_view.xml',
        'views/distrib_theme.xml',
        'views/distrib_channels.xml',
        'data/type_of_marketings.xml',
        'views/type_of_marketings.xml',
        'views/res_config_settings_views.xml',
        'views/distrib_expenses.xml',
        'views/sales_dashboard.xml',
        'views/import_move.xml',
        'views/import_inventory.xml',
        'views/import_expenses.xml',
        'data/sale_channels.xml',
        'data/regions.xml',
        'reports/report_xls.xml',
        'views/distrib_budgets.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ug_base_distrib/static/src/components/**/*.js',
            'ug_base_distrib/static/src/components/**/*.xml',
            'ug_base_distrib/static/src/components/**/*.scss',
            'ug_base_distrib/static/src/views/**/*.js',
            'ug_base_distrib/static/src/views/**/*.xml',
        ],
    },
    'depends': [
        'base',
        'product',
    ],
}
